### ISSUE TITLE
Inicializar e criar fila de mensagens

### ISSUE THREAD

**Issue by alexnsouza6** [Adamacenog/Gerente-de-execucao--SO#1]
Utilizar diretivas msgget, msgrcv para criação

**Comment by Adamacenog** [comment]
A fila de mensagem está sendo inicializada no escalonador, a diferenciação da comunicação entre o gerente de execução, executa postergado e escalonador se dá a partir de diferentes mtypes. O escalonador já está pronto e executando, faltando apenas o tratamento do término dele (criado nova issue para isso). O gerente de processos ainda precisa de implementações para ser finalizado.
