### ISSUE TITLE
Criar tabela de gerentes de execução

### ISSUE THREAD

**Issue by alexnsouza6** [Adamacenog/Gerente-de-execucao--SO#3]

**Comment by alexnsouza6** [comment]
- Alguns processos podem terminar a execução do programa antes ou depois  
    Processos vão comunicar o término do programa por meio de SIGNALS, enviando
    especificamente o SIGNAL ao processo de pid adjacente

**Comment by Adamacenog** [comment]
Foi feito o uso de signal apenas para a comunicação de termino do programa, atraves do sinal SIGTERM. Outras comunicações são feitas por fila de mensagens entre o escalonador e o nó zero. E dentro da topologia, entre os nós, de acordo com a topologia. A tabela referente as mensagens se são novas, respostas etc entre os nós, foi feita por uma struct dentro do processManager, 'floodTable'.
